SET PATH=%PATH%;.\tools
gradlew downloadKddDatasetFiles unzipKddDatasetFiles tableImportKddTrainDataFromCommandLine schemaChangeAfterImport CreateArffFileForFullTrainingAndTestDatasetGRunner trainAllModelsUsingWekaInTrainingDataSet testAllModelsUsingWekaInTrainingDataSet testAllModelsUsingWekaInTestDataSet

