export PATH=$PATH:`pwd`/tools
./gradlew clean downloadKddDatasetFiles unzipKddDatasetFiles tableImportKddTrainDataFromCommandLine execSQLSchemaChangeAfterImport execCreateArffFileFromDatabase execTrainModelsUsingDifferentClassifiersInTrainingDataSet

