export PATH=$PATH:`pwd`/tools
./gradlew downloadKddDatasetFiles unzipKddDatasetFiles tableImportKddTrainDataFromCommandLine schemaChangeAfterImport CreateArffFileForFullTrainingAndTestDatasetGRunner trainAllModelsUsingWekaInTrainingDataSet testAllModelsUsingWekaInTrainingDataSet testAllModelsUsingWekaInTestDataSet


