export PATH=$PATH:`pwd`/tools
./gradlew downloadKddDatasetFiles unzipKddDatasetFiles tableImportKddTrainDataFromCommandLine schemaChangeAfterImport createArffFileFromDatabase trainAllModelInTrainingDataSet testAllModelsInTrainingDataSet testAllModelsInTrainingDataSet

